#!/usr/bin/python3

import argparse
import io
import subprocess
import threading

parser = argparse.ArgumentParser(
    description='sets LED on device movement, clears on timeout after last movement',
    epilog='For use with MH_AUTO_BUTTONS.  See http://github.com/manna-harbour/crkbd.')
parser.add_argument(
    '-d',
    '--device',
    required=False,
    default='/dev/input/by-id/usb-Kensington_Expert_Wireless_TB-event-mouse',
    help='/dev/input/event device path')
parser.add_argument(
    '-l',
    '--led',
    required=False,
    default='4',
    help='number as per xset')
parser.add_argument(
    '-t',
    '--timeout',
    required=False,
    default='0.75',
    help='(s)')
args = parser.parse_args()

def callback():
    global timer
    timer = False
    subprocess.run(['xset', '-led', args.led])

timer = False
f = open(args.device, "rb")
while 1:
    f.read(3)
    if timer:
        timer.cancel()
    else:
        subprocess.run(['xset', 'led', args.led])
    timer = threading.Timer(float(args.timeout), callback)
    timer.start()
